import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { DatabaseSync } from 'node:sqlite';

export const editions = [
    { date: '2026-09-03', expires: '2026-10-01', major: '2026-09-03', majorExpires: '2026-10-29', code: '2609', archive: '03_Sep_2026' },
    { date: '2026-10-01', expires: '2026-10-29', major: '2026-09-03', majorExpires: '2026-10-29', code: '2610', archive: '01_Oct_2026' },
    { date: '2026-10-29', expires: '2026-11-26', major: '2026-10-29', majorExpires: '2026-12-24', code: '2611', archive: '29_Oct_2026' }
] as const;
export const NASR_INDEX = 'https://www.faa.gov/air_traffic/flight_info/aeronav/aero_data/NASR_Subscription/';
export const TPP_ROOT = 'https://aeronav.faa.gov/upload_313-d/terminal/';
const DTPP_SEARCH = 'https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/';
const groups = ['APT', 'FRQ', 'FIX', 'NAV', 'AWY', 'PFR', 'DP', 'STAR'];
const fixture = (name: string) => fs.readFile(new URL(`../fixtures/${name}`, import.meta.url), 'utf8');
const xmlDate = (date: string) => `${date.slice(5, 7)}/${date.slice(8)}/${date.slice(2, 4)}`;
const month = (date: string) => new Date(`${date}T00:00:00Z`).toLocaleString('en-US', { month: 'short', timeZone: 'UTC' });
const coverDate = (date: string) => `${date.slice(8)} ${month(date).toUpperCase()} ${date.slice(0, 4)}`;
const csv = (row: Record<string, string | number>) => Object.keys(row).join(',') + '\n' +
    Object.values(row).map(value => `"${String(value).replaceAll('"', '""')}"`).join(',') + '\n';

// Tiny real PDFs, with printed page labels and optional Chart Supplement outlines.
// They exercise the production PDF parser without gigabytes of FAA books.
function book(start: string, end: string, supplement = false) {
    const stream = (text: string) => `<< /Length ${Buffer.byteLength(text)} >>\nstream\n${text}endstream`;
    const text = (value: string, x: number, y: number) =>
        `BT /F1 7 Tf ${x} ${y} Td (${value.replaceAll('(', '\\(').replaceAll(')', '\\)')}) Tj ET\n`;
    const page = (contents: number) => `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 405 612] /Resources << /Font << /F1 6 0 R >> >> /Contents ${contents} 0 R >>`;
    const objects = [
        `<< /Type /Catalog /Pages 2 0 R${supplement ? ' /Outlines 10 0 R' : ''} >>`,
        '<< /Type /Pages /Kids [3 0 R 4 0 R 5 0 R] /Count 3 >>',
        page(7), page(8), page(9), '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
        stream(text(`Effective: 0901Z ${coverDate(start)} to: 0901Z ${coverDate(end)}`, 20, 500) +
            (supplement ? '' : text('L13', 197, 600) + text('HAYWARD EXEC (HWD)', 20, 300))),
        stream(supplement ? text('174', 33, 582) : text('94', 197, 600) + text(`Approach ${start}`, 20, 300)),
        stream(supplement ? text('Other section', 20, 300) : text('95', 197, 600)),
        ...(supplement ? [
            '<< /Type /Outlines /First 11 0 R /Last 12 0 R /Count 2 >>',
            '<< /Title (SECTION 2: DIRECTORY) /Parent 10 0 R /Next 12 0 R /Dest [4 0 R /Fit] >>',
            '<< /Title (SECTION 3: OTHER) /Parent 10 0 R /Prev 11 0 R /Dest [5 0 R /Fit] >>'
        ] : [])
    ];
    let pdf = '%PDF-1.4\n';
    const offsets = [0];
    for (const [index, object] of objects.entries()) {
        offsets.push(Buffer.byteLength(pdf));
        pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
    }
    const xref = Buffer.byteLength(pdf);
    pdf += `xref\n0 ${offsets.length}\n0000000000 65535 f \n`;
    for (const offset of offsets.slice(1)) pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
    return `${pdf}trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
}

async function archive(root: string, filename: string, files: Record<string, string>) {
    await fs.mkdir(root, { recursive: true });
    for (const [name, contents] of Object.entries(files)) await fs.writeFile(path.join(root, name), contents);
    await promisify(execFile)('zip', ['-q', filename, ...Object.keys(files)], { cwd: root });
    return fs.readFile(path.join(root, filename));
}

export async function rolloverFeed(root: string) {
    const recorded = JSON.parse(await fixture('rollover-listings.json'));
    const responses = new Map<string, string | Buffer>(Object.entries(recorded.pages));
    // October 29 is a modeled future full edition; the September/October directory
    // shapes above are recorded FAA inputs, not generated by discovery code.
    for (const [url, body] of [...responses]) {
        if (url.includes('09-03-2026/') || url.includes('2026-09-03/')) {
            responses.set(url.replaceAll('09-03-2026', '10-29-2026').replaceAll('2026-09-03', '2026-10-29'),
                String(body).replaceAll('09-03-2026', '10-29-2026').replaceAll('2026-09-03', '2026-10-29'));
        }
    }
    responses.set(TPP_ROOT, String(responses.get(TPP_ROOT)) + '<a href="2026-10-29/">2026-10-29</a>');
    const supplements = 'https://aeronav.faa.gov/upload_313-d/supplements/';
    responses.set(supplements, String(responses.get(supplements)) +
        String(responses.get(supplements)).replaceAll('20260903', '20261029'));
    const enroute = 'https://aeronav.faa.gov/enroute/';
    responses.set(enroute, String(responses.get(enroute)) + '<a href="10-29-2026/">10-29-2026</a>');
    responses.set(NASR_INDEX, editions.map(e => `<a href="${NASR_INDEX}${e.date}/">${e.date}</a>`).join(''));
    responses.set(DTPP_SEARCH, editions.map(e =>
        `<a href="https://aeronav.faa.gov/d-tpp/${e.code}/xml_data/d-tpp_Metafile.xml">${month(e.date)} ${Number(e.date.slice(8))}&ndash;${month(e.expires)} ${Number(e.expires.slice(8))}, 2026</a>`).join(''));
    const terminal = JSON.parse(await fixture('terminal-procedures.json'));
    const cifp = await fixture('terminal-cifp.txt');
    const baseXml = await fixture('procedure-catalog.xml');
    for (const e of editions) {
        const current = e.date.replaceAll('-', '/'), major = e.major.replaceAll('-', '/');
        const point = { EFF_DATE: current, LAT_DECIMAL: 37, LONG_DECIMAL: -122 };
        const files: Record<string, string> = {
            'APT_BASE.csv': csv({ ...point, SITE_NO: '00001.', SITE_TYPE_CODE: 'A', ARPT_ID: 'SBA' }),
            'APT_RWY.csv': csv({ EFF_DATE: current, SITE_NO: '00001.', SITE_TYPE_CODE: 'A', RWY_ID: '13/31' }),
            'APT_RWY_END.csv': csv({ EFF_DATE: current, SITE_NO: '00001.', SITE_TYPE_CODE: 'A', RWY_ID: '13/31', RWY_END_ID: '13' }),
            'FRQ.csv': csv({ EFF_DATE: current, FACILITY_TYPE: 'ATCT', SERVICED_FACILITY: 'SBA', SERVICED_SITE_TYPE: 'AIRPORT',
                SERVICED_STATE: 'CA', SERVICED_COUNTRY: 'US', FREQ: '119.7', FREQ_USE: 'LCL/P' }),
            'FIX_BASE.csv': csv({ ...point, FIX_ID: 'TESTF', FIX_USE_CODE: 'WP' }),
            'NAV_BASE.csv': csv({ ...point, NAV_ID: 'TESTN', NAV_TYPE: 'VOR' }),
            'AWY_BASE.csv': csv({ EFF_DATE: major, REGULATORY: 'Y', AWY_LOCATION: 'C', AWY_ID: 'V1' }),
            'AWY_SEG_ALT.csv': csv({ EFF_DATE: major, REGULATORY: 'Y', AWY_LOCATION: 'C', AWY_ID: 'V1', POINT_SEQ: 1, FROM_POINT: 'TESTN', FROM_PT_TYPE: 'VOR', TO_POINT: '' }),
            'PFR_BASE.csv': csv({ EFF_DATE: major, ORIGIN_ID: 'SBA', DSTN_ID: 'SMO', PFR_TYPE_CODE: 'TEC', ROUTE_NO: 1, ROUTE_STRING: 'TESTF' }),
            'PFR_SEG.csv': csv({ EFF_DATE: major, ORIGIN_ID: 'SBA', DSTN_ID: 'SMO', PFR_TYPE_CODE: 'TEC', ROUTE_NO: 1, SEGMENT_SEQ: 1, SEG_VALUE: 'TESTF', SEG_TYPE: 'FIX' })
        };
        for (const [key, name] of Object.entries({ departures: 'DP_BASE', departureAirports: 'DP_APT', departureRoutes: 'DP_RTE',
            arrivals: 'STAR_BASE', arrivalAirports: 'STAR_APT', arrivalRoutes: 'STAR_RTE' })) {
            files[`${name}.csv`] = terminal[key].replaceAll('2026/09/03', major);
        }
        let links = '';
        for (const group of groups) {
            const filename = `${e.archive}_${group}_CSV.zip`;
            const url = `https://nfdc.faa.gov/webContent/28DaySub/extra/${filename}`;
            links += `<a href="${url}">${group}</a>`;
            responses.set(url, await archive(path.join(root, e.date), filename, Object.fromEntries(Object.entries(files)
                .filter(([name]) => name.startsWith(`${group}_`) || name === `${group}.csv`))));
        }
        responses.set(`${NASR_INDEX}${e.date}/`, links);
        const cifpName = `CIFP_${e.date.slice(2).replaceAll('-', '')}.zip`;
        responses.set(`https://aeronav.faa.gov/Upload_313-d/cifp/${cifpName}`,
            await archive(path.join(root, e.date), cifpName, { FAACIFP18: cifp.slice(0, 35) + e.code + cifp.slice(39) }));
        let xml = baseXml.replace('cycle="2609"', `cycle="${e.code}"`)
            .replace('from_edate="0901Z  09/03/26" to_edate="0901Z  10/01/26"',
                `from_edate="0901Z  ${xmlDate(e.date)}" to_edate="0901Z  ${xmlDate(e.expires)}"`);
        if (e.date !== e.major) xml = xml.replace('<cnpage></cnpage><bvsection></bvsection><bvpage>94</bvpage>',
            '<cnpage>94</cnpage><bvsection></bvsection><bvpage>94</bvpage>');
        responses.set(`https://aeronav.faa.gov/d-tpp/${e.code}/xml_data/d-tpp_Metafile.xml`, xml);
        if (e.date !== e.major) responses.set(`${TPP_ROOT}${e.date}/CN.pdf`, book(e.date, e.expires));
        else {
            responses.set(`${TPP_ROOT}${e.date}/SW2.pdf`, book(e.date, e.majorExpires));
            const dateCode = e.date.replaceAll('-', '');
            responses.set(`https://aeronav.faa.gov/upload_313-d/supplements/CS_SW_${dateCode}.pdf`, book(e.date, e.majorExpires, true));
            const code = `${e.date.slice(8)}${month(e.date).toUpperCase()}2026`;
            responses.set(`https://aeronav.faa.gov/afd/${code}/afd_${code}.xml`,
                `<airports from_edate="0901Z ${xmlDate(e.date)}" to_edate="0901Z ${xmlDate(e.majorExpires)}"><location state="CALIFORNIA"><airport><aptname>HAYWARD EXEC</aptname><aptcity>HAYWARD</aptcity><aptid>HWD</aptid><pages><pdf>sw_174_${code}.pdf</pdf></pages></airport></location></airports>`);
            const rasterUrl = `https://aeronav.faa.gov/visual/${e.date.slice(5)}-${e.date.slice(0, 4)}/sectional-files/San_Francisco.zip`;
            responses.set(rasterUrl, await archive(path.join(root, e.date), 'raster.zip', { 'San_Francisco_SEC.tif': `fixture raster ${e.date}` }));
        }
    }
    const history = path.join(root, 'routes.sqlite');
    const db = new DatabaseSync(history);
    db.exec(await fixture('route-history.sql'));
    db.close();
    const requested: string[] = [];
    const transferred: string[] = [];
    const unavailable = new Set<string>();
    const fetcher: typeof fetch = async (input, init) => {
        const url = String(input);
        requested.push(url);
        if (unavailable.has(url)) return new Response('Fixture input unavailable', { status: 404 });
        const value = responses.get(url);
        if (value === undefined) throw new Error(`Unexpected network request in rollover test: ${url}`);
        const body = Buffer.from(value);
        const etag = `"${createHash('sha256').update(body).digest('hex')}"`;
        if (new Headers(init?.headers).get('if-none-match') === etag) return new Response(null, { status: 304 });
        transferred.push(url);
        return new Response(new Uint8Array(body), { headers: { 'content-length': String(body.length), etag } });
    };
    return { fetch: fetcher, history, requested, transferred, unavailable, responses };
}
